### PR TITLE
Adding library files

### PR DESCRIPTION
**Pull request by makermelissa**

### CODE REVIEW

**Comment by makermelissa** [comment]
This has the most recent version of Fake Requests from the MagTag library so we can remove it in the various spots and it can have its own issues/PRs.

**Comment by ladyada** [comment]
fyi - do the magtag refactor release all at once because every guide will need to be updated

**Comment by makermelissa** [comment]
Yeah, this can live separately in its own repo for the moment though because the MagTag library still has its own FakeRequests living in there.

**Comment by makermelissa** [comment]
Could I please get a review on this? I need it as a dependency for my Portal Library refactor which is failing on the dependency section.

**Review by gamblor21 — APPROVED** [review]
I didn't have a chance to build it but everything looked fine. I noticed the example loads "local.txt" which isn't in the repo and may cause an issue (but I know this is early)

**Comment by makermelissa** [comment]
Thank you. Yeah, local.txt can have whatever data in it. This is more of a usage example and can be further improved upon by others.

**Pull request merged**
